// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hffvjhorttfkhzpkwgnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZnZqaG9ydHRma2h6cGt3Z252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODMxNzEsImV4cCI6MjA3MzI1OTE3MX0.lRSPZKVdZpUDGOZAbRq0xRF6CqAxzy_fL5tlt3mjpZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});